linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - exhaustruct
    - errcheck

linters-settings:
  govet:
    enable:
      - nilness
    disable:
      - fieldalignment
      - shadow
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true

issues:
  exclude-rules:
    - path: x/gravity/abci.go
      linters:
        - dupl
    - path: config/
      linters:
        - exhaustruct
    - path: contrib/
      linters:
        - exhaustruct
        - errcheck
    - path: proto/
      linters:
        - exhaustruct
        - errcheck
    - path: third_party/
      linters:
        - exhaustruct
        - errcheck
