[package]
authors = ["Justin Kilpatrick <justin@althea.net>"]
edition = "2018"
name = "proto_build"
version = "0.1.0"

[dependencies]
prost-build = "0.11"
regex = "1.5"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tonic-build = "0.8"
walkdir = "2"
